plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
//	id "net.ltgt.errorprone" version "${error_prone_plugin_version}"
}

version = mod_version

repositories {
	maven {
		name = "Nucleoid"
		url = uri("https://maven.nucleoid.xyz")
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"polycard" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	runs {
		client {
			getProgramArguments().addAll(["--username", "RenardElectric", "--uuid", "81c5680f-418c-4389-8d5e-e319eb861ed6"])
		}
	}

	accessWidenerPath = file("src/main/resources/polycard.classtweaker")
}

fabricApi {
	configureDataGeneration() {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
	implementation "eu.pb4:sgui:${sgui_version}"
	include "eu.pb4:sgui:${sgui_version}"

//	errorprone "com.uber.nullaway:nullaway:${null_away_version}"
//	api "org.jspecify:jspecify:1.0.0"
//	errorprone "com.google.errorprone:error_prone_core:${error_prone_version}"
}

processResources {
	def resourceProperties = [
			version: mod_version,
			minecraft_version: minecraft_version,
			loader_version: loader_version,
			java_version: java_version,
			fabric_api_version: fabric_api_version
	]
	inputs.properties(resourceProperties)
	filesMatching("fabric.mod.json") {
		expand(resourceProperties)
	}
}

//import net.ltgt.gradle.errorprone.CheckSeverity

def targetJavaVersion = java_version as int
tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
	options.release = targetJavaVersion
	options.compilerArgs.add("-Xlint:all,-classfile")

//	options.errorprone {
//		check("NullAway", CheckSeverity.ERROR)
//		option("NullAway:AnnotatedPackages", "polycube.polycard")
//		option("NullAway:UnannotatedClasses", "net.minecraft.world.level.saveddata.SavedDataType")
//	}
}

java {
	def javaVersion = JavaVersion.toVersion(targetJavaVersion)
	if (JavaVersion.current() < javaVersion) {
		toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
	}
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_$name" }
	}
}
